-- Gemeinsame Produktdatenbank für neu angelegte Produkte
create table if not exists public.catalog_products (
  id bigint generated by default as identity primary key,
  product_name text not null,
  category text not null,
  subcategory text not null,
  created_by text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists catalog_products_unique
on public.catalog_products (
  lower(product_name),
  lower(category),
  lower(subcategory)
);

alter table public.catalog_products enable row level security;

drop policy if exists "Familie darf Produkte lesen" on public.catalog_products;
drop policy if exists "Familie darf Produkte eintragen" on public.catalog_products;
drop policy if exists "Familie darf Produkte bearbeiten" on public.catalog_products;
drop policy if exists "Familie darf Produkte löschen" on public.catalog_products;

create policy "Familie darf Produkte lesen"
on public.catalog_products for select to anon using (true);

create policy "Familie darf Produkte eintragen"
on public.catalog_products for insert to anon with check (true);

create policy "Familie darf Produkte bearbeiten"
on public.catalog_products for update to anon using (true) with check (true);

create policy "Familie darf Produkte löschen"
on public.catalog_products for delete to anon using (true);

do $$
begin
  alter publication supabase_realtime add table public.catalog_products;
exception
  when duplicate_object then null;
end $$;
