-- Einmalig im Supabase SQL Editor ausführen.
-- Damit eigene Kategorien und Untergruppen auf allen iPhones synchronisiert werden.

create table if not exists public.catalog_groups (
  id bigint generated by default as identity primary key,
  category text not null,
  subcategory text,
  created_by text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists catalog_groups_unique
on public.catalog_groups (lower(category), lower(coalesce(subcategory, '')));

alter table public.catalog_groups enable row level security;

drop policy if exists "Familie darf Kategorien lesen" on public.catalog_groups;
drop policy if exists "Familie darf Kategorien eintragen" on public.catalog_groups;
drop policy if exists "Familie darf Kategorien bearbeiten" on public.catalog_groups;
drop policy if exists "Familie darf Kategorien löschen" on public.catalog_groups;

create policy "Familie darf Kategorien lesen"
on public.catalog_groups for select to anon using (true);

create policy "Familie darf Kategorien eintragen"
on public.catalog_groups for insert to anon with check (true);

create policy "Familie darf Kategorien bearbeiten"
on public.catalog_groups for update to anon using (true) with check (true);

create policy "Familie darf Kategorien löschen"
on public.catalog_groups for delete to anon using (true);

do $$
begin
  alter publication supabase_realtime add table public.catalog_groups;
exception
  when duplicate_object then null;
end $$;
