-- Aktuelles Datenbankschema der Familien-Einkaufs-App

create table if not exists public.shopping_items (
  id bigint generated by default as identity primary key,
  product_name text not null,
  category text,
  subcategory text,
  quantity integer default 1,
  note text,
  added_by text not null,
  added_at timestamptz not null default now(),
  purchased boolean not null default false,
  purchased_by text,
  purchased_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.shopping_items enable row level security;

drop policy if exists "Familie darf Einkaufsliste lesen" on public.shopping_items;
drop policy if exists "Familie darf Produkte eintragen" on public.shopping_items;
drop policy if exists "Familie darf Produkte bearbeiten" on public.shopping_items;
drop policy if exists "Familie darf Produkte löschen" on public.shopping_items;

create policy "Familie darf Einkaufsliste lesen" on public.shopping_items for select to anon using (true);
create policy "Familie darf Produkte eintragen" on public.shopping_items for insert to anon with check (true);
create policy "Familie darf Produkte bearbeiten" on public.shopping_items for update to anon using (true) with check (true);
create policy "Familie darf Produkte löschen" on public.shopping_items for delete to anon using (true);

do $$
begin
  alter publication supabase_realtime add table public.shopping_items;
exception
  when duplicate_object then null;
end $$;

create table if not exists public.catalog_groups (
  id bigint generated by default as identity primary key,
  category text not null,
  subcategory text,
  created_by text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists catalog_groups_unique
on public.catalog_groups (lower(category), lower(coalesce(subcategory, '')));

alter table public.catalog_groups enable row level security;

drop policy if exists "Familie darf Kategorien lesen" on public.catalog_groups;
drop policy if exists "Familie darf Kategorien eintragen" on public.catalog_groups;
drop policy if exists "Familie darf Kategorien bearbeiten" on public.catalog_groups;
drop policy if exists "Familie darf Kategorien löschen" on public.catalog_groups;

create policy "Familie darf Kategorien lesen" on public.catalog_groups for select to anon using (true);
create policy "Familie darf Kategorien eintragen" on public.catalog_groups for insert to anon with check (true);
create policy "Familie darf Kategorien bearbeiten" on public.catalog_groups for update to anon using (true) with check (true);
create policy "Familie darf Kategorien löschen" on public.catalog_groups for delete to anon using (true);

do $$
begin
  alter publication supabase_realtime add table public.catalog_groups;
exception
  when duplicate_object then null;
end $$;
