create table if not exists public.shopping_items (
  id bigint generated by default as identity primary key,
  household_id text not null,
  name text not null,
  category text not null,
  subgroup text not null,
  added_by text not null,
  purchased boolean not null default false,
  purchased_by text,
  purchased_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.shopping_items enable row level security;

drop policy if exists "family shopping read" on public.shopping_items;
drop policy if exists "family shopping insert" on public.shopping_items;
drop policy if exists "family shopping update" on public.shopping_items;
drop policy if exists "family shopping delete" on public.shopping_items;

create policy "family shopping read" on public.shopping_items for select using (household_id = 'leon-papi-mami-anouk');
create policy "family shopping insert" on public.shopping_items for insert with check (household_id = 'leon-papi-mami-anouk');
create policy "family shopping update" on public.shopping_items for update using (household_id = 'leon-papi-mami-anouk') with check (household_id = 'leon-papi-mami-anouk');
create policy "family shopping delete" on public.shopping_items for delete using (household_id = 'leon-papi-mami-anouk');

alter publication supabase_realtime add table public.shopping_items;
