-- Persönliche Wochenlisten pro Profil und Kalenderwoche
create table if not exists public.weekly_shopping_items (
  id bigint generated by default as identity primary key,
  owner text not null,
  week_start date not null,
  product_name text not null,
  category text,
  subcategory text,
  purchased boolean not null default false,
  purchased_at timestamptz,
  added_at timestamptz not null default now()
);

create index if not exists weekly_shopping_items_owner_week_idx
on public.weekly_shopping_items (owner, week_start);

alter table public.weekly_shopping_items enable row level security;

drop policy if exists "Familie darf Wochenlisten lesen" on public.weekly_shopping_items;
drop policy if exists "Familie darf Wochenlisten eintragen" on public.weekly_shopping_items;
drop policy if exists "Familie darf Wochenlisten bearbeiten" on public.weekly_shopping_items;
drop policy if exists "Familie darf Wochenlisten löschen" on public.weekly_shopping_items;

create policy "Familie darf Wochenlisten lesen"
on public.weekly_shopping_items for select to anon using (true);

create policy "Familie darf Wochenlisten eintragen"
on public.weekly_shopping_items for insert to anon with check (true);

create policy "Familie darf Wochenlisten bearbeiten"
on public.weekly_shopping_items for update to anon using (true) with check (true);

create policy "Familie darf Wochenlisten löschen"
on public.weekly_shopping_items for delete to anon using (true);

do $$
begin
  alter publication supabase_realtime add table public.weekly_shopping_items;
exception
  when duplicate_object then null;
end $$;
